// Test Generated by Claude (claude.ai)
// Digunakan untuk menguji fungsional semua struktur data pada package collections:
// MinHeap, PriorityQueue, Queue, dan Stack.

package test

import (
	"fmt"
	"testing"

	"github.com/Yuseonr/uav-h3-pathfinding/algorithms/internal/collections"
)

var withSubmit = true

func TestMinHeap(t *testing.T) {
	type testCase struct {
		nama        string
		prioritas   []float64
		nodeIDs     []int32
		ekspekPeek  float64  // priority elemen terkecil yang diharapkan setelah Push semua
		ekspekUrutan []float64 // urutan priority hasil Pop berurutan
	}

	runCases := []testCase{
		{
			nama:         "3 elemen urut naik",
			prioritas:    []float64{1.0, 2.0, 3.0},
			nodeIDs:      []int32{10, 20, 30},
			ekspekPeek:   1.0,
			ekspekUrutan: []float64{1.0, 2.0, 3.0},
		},
		{
			nama:         "3 elemen urut turun",
			prioritas:    []float64{3.0, 2.0, 1.0},
			nodeIDs:      []int32{10, 20, 30},
			ekspekPeek:   1.0,
			ekspekUrutan: []float64{1.0, 2.0, 3.0},
		},
	}

	submitCases := append(runCases, []testCase{
		{
			nama:         "5 elemen acak",
			prioritas:    []float64{5.5, 0.1, 9.9, 3.3, 1.1},
			nodeIDs:      []int32{1, 2, 3, 4, 5},
			ekspekPeek:   0.1,
			ekspekUrutan: []float64{0.1, 1.1, 3.3, 5.5, 9.9},
		},
		{
			nama:         "1 elemen",
			prioritas:    []float64{7.7},
			nodeIDs:      []int32{99},
			ekspekPeek:   7.7,
			ekspekUrutan: []float64{7.7},
		},
	}...)

	testCases := runCases
	if withSubmit {
		testCases = submitCases
	}
	skipped := len(submitCases) - len(testCases)

	passCount := 0
	failCount := 0

	for _, tc := range testCases {
		// bangun MinHeap via PriorityQueue (pakai heap.Interface yang sudah benar)
		pq := collections.CreatePriorityQueue()
		for i, p := range tc.prioritas {
			pq.Push(tc.nodeIDs[i], p)
		}

		// cek Peek
		_, peekPrio, ok := pq.Peek()
		peekOK := ok && peekPrio == tc.ekspekPeek

		// cek urutan Pop
		urutanOK := true
		actual := make([]float64, len(tc.ekspekUrutan))
		for i := range tc.ekspekUrutan {
			_, prio := pq.Pop()
			actual[i] = prio
			if prio != tc.ekspekUrutan[i] {
				urutanOK = false
			}
		}

		pass := peekOK && urutanOK
		if pass {
			passCount++
			fmt.Printf(`---------------------------------
Test        : MinHeap / %s
Peek        : %.1f (ekspektasi %.1f)
Urutan Pop  : %v
Hasil       : Pass
`, tc.nama, peekPrio, tc.ekspekPeek, actual)
		} else {
			failCount++
			t.Errorf(`---------------------------------
Test        : MinHeap / %s
Peek        : %.1f (ekspektasi %.1f)
Urutan Pop  : %v (ekspektasi %v)
Hasil       : Fail
`, tc.nama, peekPrio, tc.ekspekPeek, actual, tc.ekspekUrutan)
		}
	}

	fmt.Println("---------------------------------")
	if skipped > 0 {
		fmt.Printf("%d passed, %d failed, %d skipped\n\n", passCount, failCount, skipped)
	} else {
		fmt.Printf("%d passed, %d failed\n\n", passCount, failCount)
	}
}

//                      PRIORITY QUEUE

func TestPriorityQueue(t *testing.T) {
	type testCase struct {
		nama         string
		inputs       []struct{ id int32; prio float64 }
		ekspekUrutan []float64 // urutan priority Pop yang diharapkan
		ekspekPeekID int32
	}

	runCases := []testCase{
		{
			nama: "3 elemen, Pop berurut ascending",
			inputs: []struct{ id int32; prio float64 }{
				{10, 9.0}, {20, 1.0}, {30, 5.0},
			},
			ekspekUrutan: []float64{1.0, 5.0, 9.0},
			ekspekPeekID: 20,
		},
		{
			nama: "5 elemen acak",
			inputs: []struct{ id int32; prio float64 }{
				{5, 0.5}, {1, 10.0}, {3, 3.3}, {2, 1.1}, {4, 7.7},
			},
			ekspekUrutan: []float64{0.5, 1.1, 3.3, 7.7, 10.0},
			ekspekPeekID: 5,
		},
	}

	submitCases := append(runCases, []testCase{
		{
			nama: "1 elemen",
			inputs: []struct{ id int32; prio float64 }{
				{42, 3.14},
			},
			ekspekUrutan: []float64{3.14},
			ekspekPeekID: 42,
		},
		{
			nama: "elemen dengan prioritas sama",
			inputs: []struct{ id int32; prio float64 }{
				{1, 2.0}, {2, 2.0}, {3, 2.0},
			},
			ekspekUrutan: []float64{2.0, 2.0, 2.0},
			ekspekPeekID: 1, // salah satu dari {1,2,3}, tidak di-assert ketat
		},
	}...)

	testCases := runCases
	if withSubmit {
		testCases = submitCases
	}
	skipped := len(submitCases) - len(testCases)

	passCount := 0
	failCount := 0

	for _, tc := range testCases {
		pq := collections.CreatePriorityQueue()
		for _, v := range tc.inputs {
			pq.Push(v.id, v.prio)
		}

		// cek Peek
		_, peekPrio, peekOK := pq.Peek()

		// cek urutan Pop
		actual := make([]float64, len(tc.ekspekUrutan))
		urutanOK := true
		for i := range tc.ekspekUrutan {
			_, prio := pq.Pop()
			actual[i] = prio
			if prio != tc.ekspekUrutan[i] {
				urutanOK = false
			}
		}

		emptyOK := pq.IsEmpty()
		pass := peekOK && urutanOK && emptyOK

		if pass {
			passCount++
			fmt.Printf(`---------------------------------
Test        : PriorityQueue / %s
Peek prio   : %.2f
Urutan Pop  : %v
IsEmpty     : %v (setelah semua Pop)
Hasil       : Pass
`, tc.nama, peekPrio, actual, emptyOK)
		} else {
			failCount++
			t.Errorf(`---------------------------------
Test        : PriorityQueue / %s
Peek prio   : %.2f
Urutan Pop  : %v (ekspektasi %v)
IsEmpty     : %v (ekspektasi true)
Hasil       : Fail
`, tc.nama, peekPrio, actual, tc.ekspekUrutan, emptyOK)
		}
	}

	fmt.Println("---------------------------------")
	if skipped > 0 {
		fmt.Printf("%d passed, %d failed, %d skipped\n\n", passCount, failCount, skipped)
	} else {
		fmt.Printf("%d passed, %d failed\n\n", passCount, failCount)
	}
}

//                          QUEUE (FIFO)

func TestQueue(t *testing.T) {
	type testCase struct {
		nama         string
		enqueue      []int32
		ekspekDequeue []int32 // urutan FIFO yang diharapkan
	}

	runCases := []testCase{
		{
			nama:         "3 elemen FIFO",
			enqueue:      []int32{10, 20, 30},
			ekspekDequeue: []int32{10, 20, 30},
		},
		{
			nama:         "1 elemen",
			enqueue:      []int32{99},
			ekspekDequeue: []int32{99},
		},
	}

	submitCases := append(runCases, []testCase{
		{
			nama:         "5 elemen FIFO",
			enqueue:      []int32{1, 2, 3, 4, 5},
			ekspekDequeue: []int32{1, 2, 3, 4, 5},
		},
		{
			nama:         "elemen dengan nilai sama",
			enqueue:      []int32{7, 7, 7},
			ekspekDequeue: []int32{7, 7, 7},
		},
	}...)

	testCases := runCases
	if withSubmit {
		testCases = submitCases
	}
	skipped := len(submitCases) - len(testCases)

	passCount := 0
	failCount := 0

	for _, tc := range testCases {
		q := collections.CreateQueue()

		emptyAwal := q.IsEmpty()
		for _, v := range tc.enqueue {
			q.Enqueue(v)
		}
		tidakKosongSetelahEnqueue := !q.IsEmpty()

		actual := make([]int32, len(tc.ekspekDequeue))
		urutanOK := true
		for i := range tc.ekspekDequeue {
			val, _ := q.Dequeue()
			actual[i] = val
			if val != tc.ekspekDequeue[i] {
				urutanOK = false
			}
		}

		emptyAkhir := q.IsEmpty()
		_, dequeueKosongOK := q.Dequeue() // harus false
		pass := emptyAwal && tidakKosongSetelahEnqueue && urutanOK && emptyAkhir && !dequeueKosongOK

		if pass {
			passCount++
			fmt.Printf(`---------------------------------
Test        : Queue / %s
Urutan      : %v
IsEmpty awal: %v | setelah enqueue: %v | setelah dequeue semua: %v
Dequeue kosong -> false: %v
Hasil       : Pass
`, tc.nama, actual, emptyAwal, tidakKosongSetelahEnqueue, emptyAkhir, !dequeueKosongOK)
		} else {
			failCount++
			t.Errorf(`---------------------------------
Test        : Queue / %s
Urutan      : %v (ekspektasi %v)
IsEmpty awal: %v | setelah enqueue: %v | setelah dequeue semua: %v
Dequeue kosong -> false: %v
Hasil       : Fail
`, tc.nama, actual, tc.ekspekDequeue, emptyAwal, tidakKosongSetelahEnqueue, emptyAkhir, !dequeueKosongOK)
		}
	}

	fmt.Println("---------------------------------")
	if skipped > 0 {
		fmt.Printf("%d passed, %d failed, %d skipped\n\n", passCount, failCount, skipped)
	} else {
		fmt.Printf("%d passed, %d failed\n\n", passCount, failCount)
	}
}

//                         STACK (LIFO)

func TestStack(t *testing.T) {
	type testCase struct {
		nama       string
		push       []int32
		ekspekPop  []int32 // urutan LIFO yang diharapkan
	}

	runCases := []testCase{
		{
			nama:      "3 elemen LIFO",
			push:      []int32{10, 20, 30},
			ekspekPop: []int32{30, 20, 10},
		},
		{
			nama:      "1 elemen",
			push:      []int32{55},
			ekspekPop: []int32{55},
		},
	}

	submitCases := append(runCases, []testCase{
		{
			nama:      "5 elemen LIFO",
			push:      []int32{1, 2, 3, 4, 5},
			ekspekPop: []int32{5, 4, 3, 2, 1},
		},
		{
			nama:      "elemen dengan nilai sama",
			push:      []int32{3, 3, 3},
			ekspekPop: []int32{3, 3, 3},
		},
	}...)

	testCases := runCases
	if withSubmit {
		testCases = submitCases
	}
	skipped := len(submitCases) - len(testCases)

	passCount := 0
	failCount := 0

	for _, tc := range testCases {
		s := collections.CreateStack()

		emptyAwal := s.IsEmpty()
		for _, v := range tc.push {
			s.Push(v)
		}
		tidakKosongSetelahPush := !s.IsEmpty()

		actual := make([]int32, len(tc.ekspekPop))
		urutanOK := true
		for i := range tc.ekspekPop {
			val, _ := s.Pop()
			actual[i] = val
			if val != tc.ekspekPop[i] {
				urutanOK = false
			}
		}

		emptyAkhir := s.IsEmpty()
		_, popKosongOK := s.Pop() // harus false
		pass := emptyAwal && tidakKosongSetelahPush && urutanOK && emptyAkhir && !popKosongOK

		if pass {
			passCount++
			fmt.Printf(`---------------------------------
Test        : Stack / %s
Urutan      : %v
IsEmpty awal: %v | setelah push: %v | setelah pop semua: %v
Pop kosong -> false: %v
Hasil       : Pass
`, tc.nama, actual, emptyAwal, tidakKosongSetelahPush, emptyAkhir, !popKosongOK)
		} else {
			failCount++
			t.Errorf(`---------------------------------
Test        : Stack / %s
Urutan      : %v (ekspektasi %v)
IsEmpty awal: %v | setelah push: %v | setelah pop semua: %v
Pop kosong -> false: %v
Hasil       : Fail
`, tc.nama, actual, tc.ekspekPop, emptyAwal, tidakKosongSetelahPush, emptyAkhir, !popKosongOK)
		}
	}

	fmt.Println("---------------------------------")
	if skipped > 0 {
		fmt.Printf("%d passed, %d failed, %d skipped\n\n", passCount, failCount, skipped)
	} else {
		fmt.Printf("%d passed, %d failed\n\n", passCount, failCount)
	}
}