// Test Generated by Claude (claude.ai)
// digunakan untuk menguji performa loading graf H3 dari file JSON, termasuk penggunaan memori dan waktu eksekusi.

package test

import (
	"fmt"
	"runtime"
	"testing"
	"time"

	"github.com/Yuseonr/uav-h3-pathfinding/algorithms/internal/graph"
)

var jsonPaths = []string{
	"../../data/processed/h3_res9_graph.json",
	"../../data/processed/h3_res10_graph.json",
	"../../data/processed/h3_res11_graph.json",
}

func TestGrafReport(t *testing.T) {
	for _, path := range jsonPaths {
		t.Run(path, func(t *testing.T) {
			report(t, path)
		})
	}
}

func report(t *testing.T, jsonPath string) {
	t.Helper()

	fmt.Println("===========================================================")
	fmt.Println("      BENCHMARK & PROFILING SISTEM MEMORI GRAF H3          ")
	fmt.Println("===========================================================")
	fmt.Printf("File Target : %s\n", jsonPath)
	fmt.Println("-----------------------------------------------------------")

	runtime.GC()

	var memBefore runtime.MemStats
	runtime.ReadMemStats(&memBefore)

	waktuMulai := time.Now()

	grafMemori, err := graph.LoadJsonGraph(jsonPath)
	if err != nil {
		t.Logf("❌ Gagal memuat graf: %v", err)
		return
	}

	durasiProses := time.Since(waktuMulai)

	var memAfter runtime.MemStats
	runtime.ReadMemStats(&memAfter)

	totalNodes := len(grafMemori.Nodes)
	var totalEdges int64
	for _, node := range grafMemori.Nodes {
		if node != nil {
			totalEdges += int64(len(node.Neighbors))
		}
	}

	memoriAllocated := float64(memAfter.Alloc-memBefore.Alloc) / 1024 / 1024
	memoriSistem    := float64(memAfter.Sys) / 1024 / 1024
	jumlahGC        := memAfter.NumGC - memBefore.NumGC

	fmt.Println("⏱️  METRIK WAKTU KOMPUTASI:")
	fmt.Printf("   -> Total Waktu Eksekusi    : %v\n", durasiProses)
	fmt.Printf("   -> Waktu Eksekusi (ms)     : %d ms\n", durasiProses.Milliseconds())
	fmt.Println()

	fmt.Println("⬡  METRIK TOPOLOGI SPASIAL GRAF:")
	fmt.Printf("   -> Total Node (Heksagon)   : %d\n", totalNodes)
	fmt.Printf("   -> Total Edge (Koneksi)    : %d\n", totalEdges)
	if totalNodes > 0 {
		fmt.Printf("   -> Rata-rata Derajat/Node  : %.2f tetangga\n", float64(totalEdges)/float64(totalNodes))
	}
	fmt.Println()

	fmt.Println("📊 METRIK EFISIENSI MEMORI (RAM):")
	fmt.Printf("   -> Alokasi Aktual Graf     : %.3f MB\n", memoriAllocated)
	fmt.Printf("   -> Residen Memori OS (Sys) : %.3f MB\n", memoriSistem)
	fmt.Printf("   -> Siklus Pembersihan GC   : %d kali\n", jumlahGC)
	fmt.Println("===========================================================")

	fmt.Println("🔍 Menjalankan Uji Validitas Data Pointer...")
	if totalNodes > 0 {
		var sampleID int32 = 0
		if h3String, exists := grafMemori.Mapper.GetH3(sampleID); exists {
			node := grafMemori.Nodes[sampleID]
			fmt.Printf("   [SUKSES] ID %d -> H3: %s\n", sampleID, h3String)
			fmt.Printf("   [SUKSES] Lat %.6f, Lng %.6f, Tetangga: %d\n",
				node.Lat, node.Lng, len(node.Neighbors))
		} else {
			fmt.Println("   [INFO] Mapper tidak menemukan sample ID 0")
		}
	}
	fmt.Print("===========================================================\n\n\n\n")
}